name: Release prettier-plugin-glsl

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/prettier-plugin-glsl

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: npm ci
        working-directory: .

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Tag
        run: |
          VERSION=$(jq --raw-output .version package.json)
          TAG="prettier-plugin-glsl-v${VERSION}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${TAG}"
          git push origin "${TAG}"

      - name: Publish to npm
        run: npm publish
